### ISSUE TITLE
Core MVP

### ISSUE THREAD

**Issue by Sn0wye** [Sn0wye/caho#5]
# To-dos

- [x] Search for public lobbies screen
- [x] Join private room modal
- [x] Toast
- [x] Mobile responsiveness
- [ ] 404 screen
- [ ] Reconnect screen
- [ ] Card placeholders (fill in the gap)
- [ ] Remove css keyframes and replace them by `@apply`
- [ ] Override number input to remove caret on the right
- [ ] Disconnected toast

## Code to-dos
- [x] Animate ranking and navbar collapse
- [ ] Clipboard room code
- [ ] Infer game component props from zod schemas

## Backend edge cases
- [ ] Room edge cases

# Other
- [x] TRPC Errors

# Dashboard
- [x] Create room button link

# Profile
- [ ] Image upload

# Auth
- [ ] Enhance Register flow

# Join Private room
- [x] Room code uppercase front-end formating
- [ ] Update player join realtime
- [ ] Update UI on ready status (LOBY room)

# Game
- [ ] Select card
- [ ] Throw card
- [ ] Judge mode
- [x] Points
- [x] Player list

**Comment by ruymon** [comment]
![image](https://github.com/Sn0wye/caho/assets/50504050/be6531cb-08de-4263-ad0f-0d23d43c37c7)

**Comment by Sn0wye** [comment]
> ![image](https://user-images.githubusercontent.com/50504050/258610332-be6531cb-08de-4263-ad0f-0d23d43c37c7.png)

gostei hein

**Comment by ruymon** [comment]
@Sn0wye Vou usar isso como inspiração para fazer. Aproveita e coloca uma task nesse issue para isso.

**Comment by Sn0wye** [comment]
> @Sn0wye Vou usar isso como inspiração para fazer. Aproveita e coloca uma task nesse issue para isso.

Hey @ruymon, tem algo que já foi feito daqui?
